stat s3
robertstettner/drone-cloudformation pull request #2
Opened 2017-08-22 09:15 UTC by nchinan

.flatMap(fs.statStream) will throws an exception when an s3 bucket uri is supplied.  I have just set the path to '/' in this case for the check.

2017-08-22 17:38 UTC, robertstettner commented
There is a better way. Change the condition here: https://github.com/nchinan/drone-cloudformation/blob/fd3ef84e465f383b044a5de9d3dda642a949f6e7/plugin.js#L104

2017-08-23 08:18 UTC, nchinan commented
I prefer something like

`const hl = require('highland');
const path = require('path');
let fs = hl.streamifyAll(require('fs'));


let resolveAbosolutePath = p => path.resolve(process.cwd(), p);


const p = ['./node_modules', 's3://mybucket/file.zip', 'https://s3.mybucket.com/file.zip'];

if (process.env.ADD_BAD_FILE) {
        p.push('./asdfasdfsda');
}

let s = hl(p)
        .reject(x => /s3:\/\//.test(x) || /https:\/\//.test(x))
        .map(resolveAbosolutePath)
        .flatMap(fs.statStream)
        .collect()
        .toCallback(err => {
                if (err) {
                        console.error(err);
                        return process.exit(1);
                }
                process.exit(0);
        });


`

2017-08-23 15:00 UTC, robertstettner requested changes
Could you add a unit test for this here: https://github.com/robertstettner/drone-cloudformation/blob/d5da579286270adf686532ac91309c1a66d6ffea/test/unit.spec.js#L549

2017-08-23 15:00 UTC, robertstettner commented on plugin.js
> +                return hl([env.PLUGIN_TEMPLATE])
Please use the `of` method instead of encapsulating the template in an array.

2017-08-24 11:23 UTC, robertstettner commented
Please remove the `.swp` file, and while you there, could you please add that extension to the `.gitignore` file?

2017-08-24 11:34 UTC, robertstettner approved these changes

2017-08-24 11:35 UTC, merged